# Generated by Django 3.1.7 on 2022-06-13 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgr_models', '0010_report_owner_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminReport',
            fields=[
                ('lgrreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lgr_models.lgrreport')),
            ],
            bases=('lgr_models.lgrreport',),
        ),
    ]
