# Generated by Django 3.1.7 on 2022-05-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0007_populate_unicode_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='msr',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rzlgr',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
