# Generated by Django 3.1.7 on 2022-06-17 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0009_lgrsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnicodeVersion',
        ),
    ]
