# Generated by Django 3.1.7 on 2022-09-06 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0011_reflgr_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgrsettings',
            name='variant_calculation_abort',
            field=models.PositiveIntegerField(default=1000000, validators=[django.core.validators.MinValueValidator(4)]),
            preserve_default=False,
        ),
    ]
