# Generated by Django 3.1.7 on 2023-06-07 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0012_lgrsettings_variant_calculation_abort'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgrreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lgrsettings',
            name='report_expiration_delay',
            field=models.PositiveIntegerField(default=30),
            preserve_default=False,
        ),
    ]
