# Generated by Django 3.1.14 on 2023-07-07 16:01

from django.db import migrations, models
import django.utils.timezone
import lgr_models.models.lgr
import lgr_models.storage


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0014_auto_20230703_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgrsettings',
            name='report_expiration_last_run',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reflgrmember',
            name='file',
            field=models.FileField(storage=lgr_models.storage.LGROverrideStorage, upload_to=lgr_models.models.lgr.get_upload_path),
        ),
        migrations.AlterField(
            model_name='rzlgrmember',
            name='file',
            field=models.FileField(storage=lgr_models.storage.LGROverrideStorage, upload_to=lgr_models.models.lgr.get_upload_path),
        ),
    ]
