# Generated by Django 5.2.6 on 2025-10-02 14:40

import lgr_models.models.report
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0015_auto_20230707_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lgrreport',
            options={'ordering': ['file']},
        ),
        migrations.AlterField(
            model_name='lgrreport',
            name='file',
            field=models.FileField(max_length=256, upload_to=lgr_models.models.report.get_upload_path),
        ),
    ]
