# Generated by Django 5.2.6 on 2025-10-02 14:42

import lgr_models.models.lgr
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_models', '0016_alter_lgrreport_options_alter_lgrreport_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryLgrBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lgr_models.models.lgr.get_upload_path)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
