# Generated by Django 2.2.1 on 2021-02-01 16:49

from django.db import migrations, models
import django.db.models.deletion
import lgr_idn_table_review.admin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefLgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lgr_idn_table_review.admin.models.get_upload_path)),
                ('name', models.CharField(max_length=128)),
                ('language_script', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RzLgr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lgr_idn_table_review.admin.models.get_upload_path)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RzLgrMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=lgr_idn_table_review.admin.models.get_upload_path)),
                ('name', models.CharField(max_length=128)),
                ('rz_lgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository', to='admin.RzLgr')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
