cluster: ocp
env: prod
region: dc
namespace: contracted-parties
app: lgr

replicaCount: 1
historyLimit: 3

serviceAccount: sa-icannhostpathroot

volume:
  storage:
    name: nfsstorage
    remotePath: /var/mnt/www/idntable
    localPath: /var/www/lgr/src/lgr_web/storage

lgr:
  URL: lgrtool.icann.org
  Email: idnprogram@icann.org

  Sentinel1: redis1.dc.icann.org
  Sentinel2: redis2.dc.icann.org
  Sentinel3: redis3.dc.icann.org

  sentinelPort: 26379

  CeleryRedisDB: 5
  DjangoRedisDB: 6
  SentinelMaster: mymaster

  IcannAuthUrl: https://account.icann.org

repoPath: artifactory.icann.org/docker/icann
repoVer: latest

microservices:
  gunicorn:
    name: gunicorn
    image: lgr-gunicorn
    volume: true
    smtp: true
    uid: 30404
    gid: 0
    web:
      path: /
      pathType: Prefix
      port: 8000
      protocol: TCP
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 2Gi

  static:
    name: static
    image: lgr-static
    uid: 0
    gid: 0
    web:
      path: /static
      pathType: Prefix
      port: 8000
      protocol: TCP
      nodePort: 32100
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 1Gi

  celery:
    name: celery
    image: lgr-celery
    uid: 30404
    gid: 0
    volume: true
    smtp: true
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 200m
        memory: 2Gi

  beat:
    name: beat
    image: lgr-celery
    uid: 30404
    gid: 0
    volume: true
    args: ["beat"]
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 128Mi

smtp:
  name: smtp
  image: container-registry.icann.org/base-images/postfix-container.icann.org
  email: idnprogram@icann.org
  port: 25
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 128Mi
