# Generated by Django 3.1.7 on 2022-08-26 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('lgr_advanced', '0002_tmplgrmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgrmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'lgr_models'), ('model', 'RzLgr')), models.Q(('app_label', 'lgr_models'), ('model', 'MSR')), models.Q(('app_label', 'lgr_models'), ('model', 'IDNARepertoire')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='setlgrmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'lgr_models'), ('model', 'RzLgr')), models.Q(('app_label', 'lgr_models'), ('model', 'MSR')), models.Q(('app_label', 'lgr_models'), ('model', 'IDNARepertoire')), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
