# Generated by Django 3.1.7 on 2021-09-02 16:15

from django.db import migrations, models
import django.utils.timezone
import lgr_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LgrUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', lgr_auth.models.UAEmailField(error_messages={'unique': 'An user with that email already exists.'}, help_text='Required. Valid email address', max_length=254, unique=True)),
                ('role', models.CharField(choices=[('User', 'User'), ('ICANN', 'ICANN'), ('Admin', 'Admin')], default='User', max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
            },
        ),
    ]
