# Generated by Django 3.1.7 on 2022-09-09 19:56

from django.db import migrations, models
import lgr_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lgruser',
            name='icann_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lgruser',
            name='email',
            field=lgr_auth.models.UAEmailField(error_messages={'unique': 'An user with that email already exists.'}, help_text='Required. Valid email address', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lgruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='lgruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
    ]
