# Generated by Django 5.2.6 on 2025-10-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lgr_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lgrtaskmodel',
            options={},
        ),
    ]
