# Generated by Django 3.1.7 on 2022-05-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lgr_models', '0008_add_active_field_in_rz_lgr_and_msr'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGRToolReport',
            fields=[
                ('lgrreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lgr_models.lgrreport')),
            ],
            bases=('lgr_models.lgrreport',),
        ),
    ]
